# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
variables:
  rabbitmq:
    host:
      value: jx-staging-rabbitmq
    username:
      value: guest
    password:
      value: guest
container:
  javaOpts: -Xmx512m -Xms512m
image:
  repository: 100.64.99.139:5000/activiti/ttc-connectors-processing
  tag: 1.0.0
  pullPolicy: IfNotPresent
service:
  name: ttc-connectors-processing
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 400m
    memory: 768Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 90
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
